apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyPrivileged
metadata:
  name: deny-privileged-audit-zone
spec:
  enforcementAction: deny
  match:
    namespaces: ["audit-zone"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
